# Base configs
baseurl: "https://www.nicolaswdc.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-00000000-2"

# UI configs
title: "Photography by Nicolas Winkler"
subtitle: "See the world through my eyes!"
author: "Nicolas Winkler"
header:
 title: "Nicolas"
 subtitle: "Winkler"
footer:
 name: "Hey there, my name is Nico"
 bio: "I am a student and a amateur photographer from Germany. Love doing some random photo editing and now learning programming."
 github: "Want a website like this for yourself? Just <a href=\"https://github.com/nicodotcin/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  #facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/elonmusk"
  instagram: "https://www.pleasedontstalkme.haha"
  #dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://www.linkedin.com/in/nicolas-winkler-640a99205/"
  github: "https://www.github.com/nicodotcin"
